name: CI

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
  pull_request:
  workflow_dispatch:

jobs:
  rust:
    name: fmt + clippy + test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal --component rustfmt --component clippy

      - uses: Swatinem/rust-cache@master

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Test
        run: cargo test --all
